// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhyD7NtqZ6e8-ob3oGatw4CQ0LYqEZak',
    appId: '1:577742085986:web:7a345a001550165ad9163b',
    messagingSenderId: '577742085986',
    projectId: 'cook-cea38',
    authDomain: 'cook-cea38.firebaseapp.com',
    storageBucket: 'cook-cea38.firebasestorage.app',
    measurementId: 'G-4KFF0B8JP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftGWd1btma2Rz39Gvu3WrspCLLR-ga60',
    appId: '1:577742085986:android:a303b7eb5f837d26d9163b',
    messagingSenderId: '577742085986',
    projectId: 'cook-cea38',
    storageBucket: 'cook-cea38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_487wpbfTaovHAt6f5JYZXmiI_oSQ_fQ',
    appId: '1:577742085986:ios:17394a91767b3d0cd9163b',
    messagingSenderId: '577742085986',
    projectId: 'cook-cea38',
    storageBucket: 'cook-cea38.firebasestorage.app',
    iosBundleId: 'com.example.fnPrj',
  );

}